window.chapters = [
"En el corazón de la llanura de Azur reinaba el Emperador Felino, un gobernante de ojos dorados y pelaje de sombra; su andar imponía respeto y su voz, ley. Las ciudades a sus pies acudían con tributo y los vientos contaban historias de su sabiduría.",
"A las afueras de la capital vivía Power, un migajero de manos rápidas y sueños grandes. Su apodo venía de su habilidad para encontrar migas de pan donde otros veían polvo: alimentaba su astucia y su esperanza.",
"Una noche, durante una lluvia de cometas, Power recogió una insignia perdida: el sello del Emperador. Al tocarlo, sintió un calor que no era suyo y entendió que el destino le pedía algo más que migas.",
"El Emperador, curioso por la lealtad de su pueblo, ordenó una fiesta en la plaza mayor. Entre las antorchas y la música, un mensajero anunció la aparición de Power sosteniendo el sello; la multitud contuvo la respiración.",
"Llamado ante la corte, Power se inclinó con la simpleza que lo caracterizaba. El Emperador observó su mirada franca y, por un instante, vio en él la honestidad que le faltaba a muchos nobles.",
"El consejo murmuró: ¿qué puede un migajero ofrecer a un imperio? Pero el Emperador, movido por curiosidad, preguntó por su nombre. Power respondió: 'Me llaman Power, y ante mi Emperador me presentaré de rodillas'.",
"La frase resonó en la sala: 'De rodillas ante mi Emperador' se convirtió en el nombre ceremonial con el que la corte recordaría aquel encuentro. Power sonrió con humildad y no con vergüenza.",
"Los días que siguieron, Power fue asignado a la despensa real, pero su ingenio pronto cruzó muros: reorganizó almacenes, mejoró rutas y mostró una lealtad que no pedía recompensa.",
"En secreto, el Emperador lo observaba desde una ventana, aprendiendo a medir el valor más allá de títulos. Power, mientras tanto, hablaba con la gente sencilla: comerciantes, panaderos y músicos.",
"La ciudad empezó a prosperar de una manera silenciosa; las calles eran más limpias, los hornos más calientes y los niños corrían con migas en las manos. Power se convirtió en un puente entre el trono y la plaza.",
"Un mercader ambicioso intentó corromper a un funcionario para desviar impuestos, y Power lo descubrió por casualidad. En vez de denunciar públicamente, trazó un plan para exponer la red de engaños.",
"La noche de la revelación, el Emperador convocó al mercader y al funcionario; la verdad, desmontada por las pruebas de Power, dejó en vergüenza a los culpables. La corte entendió que la lealtad se presenta en acciones.",
"La fama de Power creció y con ella la envidia de algunos nobles que temían perder influencia. Susurros se convirtieron en promesas rotas y en miradas calculadas en los corredores del palacio.",
"El Emperador, lejos de detener a Power, le ofreció una misión peligrosa: viajar a las fronteras y negociar con el clan de las Arenas para evitar una guerra por el agua.",
"Power aceptó la tarea con la sencillez de quien no se siente digno ni indigno: partió con una pequeña bolsa de provisiones y la bendición del pueblo. Su nombre, ya sabido por la plaza, era murmurado con orgullo.",
"En las llanuras, encontró caminos secos y caravanas exhaustas. Su trato fue honesto; supo ofrecer pan y palabra cuando los jefes del clan escuchaban más a quienes daban que a los que prometían.",
"Las negociaciones fueron largas; hubo noches de dudas y días de esperanza. Power demostró que la humildad puede tejer acuerdos donde la arrogancia solo siembra desdén.",
"Al regresar, recibió una sorpresa: el Emperador lo aguardaba en el pórtico con un regalo sencillo: una capa de trabajo con un bordado dorado. Power la llevó con respeto y la puso a secar al sol.",
"La corte, antes reticente, empezó a ver el valor práctico de la cercanía al pueblo. Costumbres antiguas, que favorecían la altura sobre la honestidad, comenzaron a cambiar lentamente.",
"Pero no todo era calma; un grupo de nobles conservadores, temiendo perder poder, urdió una trampa para desacreditar a Power: plantar pruebas de robo en su mochila.",
"La acusación cayó como lluvia ácida sobre la reputación de Power. Fue arrojado a una prisión humilde, y la ciudad se dividió entre quienes aún confiaban y quienes preferían creer en lo cómodo.",
"En la celda, Power recordó las palabras de su madre: 'La dignidad no viene de lo que te llaman, sino de cómo te levantas'. Escribió una carta al Emperador con tinta robada de un sapo de tinta.",
"El Emperador leyó la carta y sintió un remolino de emociones: culpa por no haberlo protegido y miedo por la marea de la opinión. Ordenó una investigación silenciosa y pidió pruebas.",
"Mientras las sombras crecían, Power mantuvo la calma. Sus compañeros de prisión, hombres y mujeres de la calle, lo cuidaban con pequeñas migas de esperanza que él mismo compartía.",
"La pesquisa destapó a los nobles conspiradores: testimonios, cuentas y antiguas rencillas salieron a la luz. La evidencia fue clara y la corte no pudo obviarla.",
"Los responsables fueron expulsados, pero el Emperador tomó una decisión más difícil: reconoció que su corte había sido ciega y que su culpa era colectiva. Prometió reformas.",
"Power fue liberado con honores. Al salir, la gente le aplaudió con lágrimas y pan; él, con humildad, solo pidió que la justicia no fuera una palabra vacía.",
"Con la confianza restaurada, Power fue nombrado Guardián de las Rutas: su tarea era asegurar que los bienes del imperio llegaran a todos sin robo ni favoritismos.",
"Bajo su custodia, las rutas mejoraron; los mensajes llegaron más rápidos y los comerciantes confiaron en códigos simples que eliminaban tratos oscuros. La prosperidad se sintió.",
"Un invierno, la peste atacó a una región y los suministros escasearon. Power organizó filas, repartió migas de pan y creó refugios improvisados con mantas del mercado.",
"El Emperador, observando desde su sala, mandó médicos y apoyo; juntos evitaron una catástrofe. Esa alianza, forjada en acción y confianza, se convirtió en leyenda en las tabernas.",
"Pero la seguridad atrajo la atención: un reino vecino, envidioso de la prosperidad, envió emisarios con promesas y espías con dagas ocultas. Se acercaba la tempestad.",
"Power preparó a las rutas con señales y faros; pocos sabían que su inteligencia venía de escuchar al panadero que describía las caravanas. El Emperador, por su parte, afinó su estrategia militar.",
"Las tensiones crecieron hasta que un día, en la frontera, un mensajero enemigo cruzó con una oferta de paz. Algunos juraron aceptar; otros, preparar la guerra inmediata.",
"Power aconsejó prudencia: negociar bajo condiciones claras. Su voz, más humana que la de los generales, habló de vidas y panes, no solo de banderas y honor.",
"La paz se firmó con pactos de intercambio y vigilancia mutua. Las voces que clamaban por sangre se silenciaron ante la evidencia de que la guerra traería hambre.",
"Con el tiempo la historia del acuerdo se volvió enseñanza en las escuelas: 'Primero escucha, luego habla' enseñaba la maestra usando el ejemplo de Power.",
"La calma permitió que la cultura floreciera: poetas cantaron las calles, músicos llenaron plazas y los mercados ofrecieron sabores nuevos. El Emperador veía el cambio con ojos satisfechos.",
"Sin embargo, en la penumbra, un viejo consejero urdía volver a la vieja guardia. Su ambición no se disolvía con las fiestas; buscaba retomar el control por vías más sutiles.",
"Cuando llegó la cosecha, el consejero intentó monopolizar los graneros del sur con contratos falsos. Power descubrió las letras pequeñas y expuso el fraude con el apoyo de los campesinos.",
"La gente salió a las plazas, exigiendo justicia. El Emperador, sintiendo el pulso de su pueblo, ordenó abrir los graneros y redistribuir el excedente para los más necesitados.",
"Este acto cimentó la fe de la gente: un rey que comparte no es débil; es un protector. Power, sin buscar condecoraciones, recibió la gratitud que nunca imaginó.",
"En las noches claras, el Emperador y Power conversaban en el tejado del palacio; hablaban de estrellas, de números y de por qué una migaja puede encender una rebelión.",
"La amistad se fortaleció. Power aprendió a leer libros antiguos que el Emperador le prestaba, y el Emperador aprendió que la verdad no sabe de títulos.",
"La corte cambió sus costumbres: ahora los funcionarios visitaban la plaza, escuchaban quejas y resolvían en sitio. La distancia entre trono y pueblo se acortó.",
"Pero la vida trae pruebas: una sequía prolongada amenazó pozos y sembrados. Power viajó al desierto para buscar soluciones y traer fuentes alternas de agua.",
"En su viaje encontró antiguas cisternas y rescató mapas olvidados. Con su paciencia y su habilidad, sanó pozos y enseñó a la gente a conservar el agua.",
"A su regreso, fue recibido con fiestas y una pequeña estatua fue colocada en la plaza que representaba una mano que comparte pan. Un símbolo sencillo que decía más que discursos.",
"La paz que siguió permitió que el Emperador proclamara una ley: 'Quien cuide las rutas cuidará al pueblo.' Power recibió la investidura en una ceremonia humilde.",
"La envidia persistente nunca desapareció por completo. Un grupo disperso intentó incendiar un almacén; Power, con su rapidez, alertó a los guardias y evitó la tragedia.",
"Los conspiradores fueron capturados y encarcelados; algunos renegaron de su ambición y otros buscaron exilio. La ciudad siguió adelante, aprendiendo de cada tropiezo.",
"Años pasaron y el Emperador envejeció; su melena blanqueó y sus pasos se volvieron más lentos. Power, ya no tan joven, se convirtió en un pilar de la gobernanza cotidiana.",
"El Emperador convocó a Power y le habló con la voz que había impuesto ley en incontables ocasiones: 'El trono no es solo poder; es responsabilidad. ¿Me ayudarás a elegir a mi sucesor?'",
"Power asumió la tarea con la humildad de siempre. Organizó audiencias, escuchó propuestas y pidió tiempo para conocer a los candidatos más allá de sus títulos.",
"Entre los aspirantes había un joven con ideales, una mujer sabia y un noble reformista. Power conversó con cada uno en la plaza, entre gente como quien aprende a oler el pan.",
"El proceso fue tranquilo y transparente: el Emperador observó la elección como un padre que mira crecer a sus hijos. Al final eligió a la mujer sabia: prudente, cercana y con visión.",
"La coronación fue sencilla. Power permaneció a un lado, contento de haber aportado su experiencia. La nueva Emperatriz prometió cuidar al pueblo con el mismo celo.",
"Con la nueva era, Power recibió un sitio en el consejo pero declinó jurar lealtad formal; prefería servir sin la pompa del ajetreo. Su lugar real estaba en las calles.",
"La ciudad, bajo la Emperatriz, prosperó. Los mercados crecieron y las rutas se consolidaron en una red eficiente que hizo florecer la artesanía local.",
"El nombre 'De rodillas ante mi Emperador' quedó como recuerdo de humildad: una canción que los niños aprendían para recordar que el respeto no requiere sumisión ciega.",
"Aunque la paz reinaba, emergió un nuevo desafío: la tecnología de otros reinos traía máquinas que cambiaban el trabajo en los molinos. Algunos temían perder su oficio.",
"Power, fiel a su manera, organizó talleres para que la gente aprendiera a trabajar con las nuevas máquinas; no buscó destruir lo nuevo, sino integrarlo con cuidado.",
"El resultado fue un renacimiento productivo: más pan, mejor calidad y más tiempo libre para las familias. Los ancianos recordaban con nostalgia, pero celebraban también las mejoras.",
"El Emperador, contento, vio cómo su legado se transformaba en leyendas útiles: no solo órdenes, sino herramientas y escuelas que mantuvieran a la gente activa.",
"Aun así, la vida guardaba pruebas: un brote de descontento entre lacayos mal pagados amenazó con convertir en crimen la pobreza. Power medió con paciencia.",
"Con argumentos sencillos y propuestas reales, ofreció salarios equitativos y un sistema para que los jóvenes aprendieran oficios. La revuelta se disolvió y la esperanza creció.",
"Pasaron las estaciones y el Emperador sintió que su tiempo llegaba a su fin. Convocó a Power a su lecho y le entregó un pequeño relicario con una pluma; 'Para que escribas lo que viste'.",
"Power abrió el relicario y encontró una nota: 'No seas un rey, sé un servidor'. Esa frase lo acompañaría en las décadas que siguieron como guía silenciosa.",
"Tras la muerte del Emperador, la ciudad lloró, pero celebró su vida con una procesión donde el pueblo portó antorchas y panes. El legado de su gobierno quedó escrito en acciones.",
"Power, ahora anciano, se dedicó a escribir sus memorias: no quería títulos, solo dejar lecciones simples para quienes gobernaran después.",
"Los jóvenes le pedían historias de batallas imaginarias; él respondía con relatos de rutas y pan, enseñando que la grandeza reside en lo cotidiano.",
"Un día, un niño le preguntó por qué su nombre era tan extraño. Power respondió: 'Porque cuando me arrodillé, no fue para humillarme; fue para elevar a los demás'.",
"Las escuelas adoptaron sus enseñanzas y en las plazas se colgaban carteles con frases de su pluma: 'Comparte tu pan, comparte tu palabra, comparte tu tiempo.'",
"La ciudad, con sus altibajos, se convirtió en un ejemplo para regiones vecinas. Embajadores venían a aprender no cómo gobernar por miedo, sino cómo gobernar con servicio.",
"Power visitó un taller que él mismo había abierto años atrás; allí una mujer enseñaba a niños a amasar pan. Sonrió al ver que las migas seguían alimentando sueños.",
"La Emperatriz, ya mayor, le ofreció una estatua en el jardín real. Power rió: prefería que el jardín se usara para sembrar hortalizas. La propuesta fue aceptada: había una estatua pequeña y un huerto comunitario.",
"En su última caminata por la plaza, Power escuchó el murmullo alegre de los comerciantes y supo que no había vivido en vano. El pueblo era su remedio y su premio.",
"Antes de partir, reunió a algunos jóvenes y les enseñó a registrar las historias del pueblo. 'No olviden las pequeñas manos', dijo, 'porque sostienen las grandes decisiones'.",
"Cuando Power murió, la ciudad lo lloró con pan y canciones. En las puertas, la gente dejó migas en memoria de quien enseñó a encontrar valor en lo sencillo.",
"Su epitafio en la plaza decía: 'Aquí yace quien juntó migas y corazones'. No era un epitafio pomposo, pero encerraba todo lo que fue su vida.",
"La leyenda creció con el tiempo: biógrafos escribieron, bardos cantaron y los niños seguían aprendiendo a compartir. Su nombre, aunque curioso, jamás fue olvidado.",
"El Emperador Felino pasó a la historia como un líder que aprendió a escuchar. Su reino perduró porque entendió que la fuerza no es el rugido, sino la mano que ayuda a levantar.",
"En las noches de luna, los viejos contaban cómo un migajero llamado 'De rodillas ante mi Emperador' cambió la ciudad con migas y sentido común. Los jóvenes reían y querían ser como él.",
"Años después, un visitante preguntó por el secreto: '¿Fue magia o suerte?' Le respondieron: 'Fue constancia y humildad'. No había hechizo, solo trabajo constante.",
"La ciudad siguió su curso, con nuevas generaciones que discutían estrategias y recetas. En los mercados, los panes llevaban un sello pequeño con la silueta de una mano.",
"El relato de Power se enseñó como materia en la escuela: no como mito distante, sino como guía para la convivencia; así, la ciudad aprendió a perpetuar su praxis.",
"Aunque muchas cosas cambiaron, la esencia quedó: el Emperador y el migajero demostraron que la distancia entre trono y barrio puede acortarse con acciones simples.",
"Y en cada esquina, en cada horno, en cada aula, la frase 'De rodillas ante mi Emperador' se recordaba no como sumisión, sino como un gesto para poner en primer lugar al otro.",
"Así concluye esta saga de cien capítulos: no con una explosión de gloria, sino con panes compartidos, rutas seguras y la memoria de que la grandeza reside en servir.",
"FIN"
];
